# Generated by Django 4.0.3 on 2022-05-06 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kahoot', '0002_participant_quiz_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='name',
            field=models.CharField(default='New quiz', max_length=200),
        ),
        migrations.AddField(
            model_name='quiz',
            name='pub_date',
            field=models.DateTimeField(default=datetime.date(2022, 5, 6), verbose_name='date published'),
        ),
    ]
