# Generated by Django 4.0.3 on 2022-05-06 10:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kahoot', '0003_quiz_name_quiz_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 6, 10, 19, 11, 679317), verbose_name='date published'),
        ),
    ]
