# Generated by Django 4.0.3 on 2022-05-10 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kahoot', '0007_game_alter_question_pub_date_delete_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game',
            new_name='quiz',
        ),
    ]
