# Generated by Django 4.0.3 on 2022-05-10 14:07

from django.db import migrations, models
import kahoot.models


class Migration(migrations.Migration):

    dependencies = [
        ('kahoot', '0008_rename_game_game_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='code',
            field=models.IntegerField(default=kahoot.models.generate_game_code),
        ),
    ]
