# Generated by Django 4.0.3 on 2022-05-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kahoot', '0010_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
