# Generated by Django 4.0.3 on 2022-05-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kahoot', '0011_participant_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.IntegerField(choices=[(0, 'Initialized'), (1, 'Started'), (2, 'ended')], default=0),
        ),
    ]
